# Generated by Django 2.2.7 on 2020-01-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='DEFAULT', max_length=7, unique=True),
        ),
    ]
