# Generated by Django 2.2.7 on 2020-01-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0003_auto_20200106_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
