# Generated by Django 2.2.7 on 2020-01-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0004_auto_20200106_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='deptt',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
