# Generated by Django 2.2.7 on 2020-01-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0008_auto_20200107_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
