# Generated by Django 2.2.7 on 2020-01-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0009_auto_20200107_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
