# Generated by Django 2.2.7 on 2020-01-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0010_auto_20200108_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
