# Generated by Django 2.2.7 on 2020-01-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_manager', '0012_auto_20200108_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
